---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.example.com
  resources:
  - appbundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.example.com
  resources:
  - appbundles/finalizers
  verbs:
  - update
- apiGroups:
  - app.example.com
  resources:
  - appbundles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - packagerevisions
  - repositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - packagevariants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - packagevariants/status
  verbs:
  - get
