apiVersion: app.example.com/v1alpha1
kind: AppBundle
metadata:
  name: appbundle-with-porch
  namespace: default
spec:
  # Controller creates PackageVariant for each porchPackageRef
  porchIntegration:
    enabled: true
    repository: mgmt  # Name of downstream Repository CR (not URL)
  
  groups:
    - name: networking
      order: 0
      components:
        - name: service-mesh
          order: 0
          # Controller creates PackageVariant -> Porch deploys
          porchPackageRef:
            packageName: istio-base                   # Package name in repository
            repository: catalog-networking            # Repository CR name
            namespace: default                        # Where PackageVariant is created
            revision: v1.0.0                          # Git branch/tag
          template:
            # Describes expected resources for readiness check
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: service-mesh-config
              namespace: default
            data:
              mesh: istio
    
    - name: monitoring
      order: 1
      components:
        - name: prometheus
          order: 0
          porchPackageRef:
            packageName: prometheus-operator          # Package name in repository
            repository: catalog-monitoring            # Repository CR name
            namespace: default                        # Where PackageVariant is created
            revision: v2.0.0                          # Git branch/tag
          template:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: monitoring
        
        - name: grafana
          order: 1
          porchPackageRef:
            packageName: grafana                      # Package name in repository
            repository: catalog-monitoring            # Repository CR name
            namespace: default                        # Where PackageVariant is created
            revision: v1.5.0                          # Git branch/tag
          template:
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: grafana-config
              namespace: monitoring
            data:
              enabled: "true"

