apiVersion: app.example.com/v1alpha1
kind: AppBundle
metadata:
  name: 0
  namespace: default
spec:
  # Porch integration - controller will create PackageVariant
  porchIntegration:
    enabled: true
    repository: https://github.com/vitu-mafeni/catalog
  
  groups:
    - name: setup
      order: 0
      components:
        - name: namespace
          order: 0
          template:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: redis-app
              labels:
                app: redis
    
    - name: redis
      order: 1
      components:
        - name: redis-workload
          order: 0
          # Controller creates PackageVariant -> Porch deploys resources
          porchPackageRef:
            name: redis                  # Package in repository
            namespace: porch-packages    # Where Porch stores packages
            revision: main               # Git branch/tag
          template:
            # Describes expected resources for readiness check
            apiVersion: v1
            kind: Service
            metadata:
              name: redis
              namespace: redis-app
            spec:
              type: ClusterIP
              selector:
                app: redis
              ports:
              - port: 6379
                targetPort: 6379

